version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./containers/database/postgres/volumes:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - production-network
  mongo:
    image: mongo:latest
    volumes:
      - ./containers/database/mongo/volumes:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - production-network

  minio:
    image: minio/minio:latest
    volumes:
      - ./containers/database/minio/volumes:/data
    ports:
      - "9000:9000"
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    networks:
      - production-network

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      
    ports:
      - "8081:8081"
    expose:
      - 8081
    networks:
      - production-network

networks:
  production-network:
    driver:
      bridge
